# Generated by Django 3.2.5 on 2021-07-14 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=300, verbose_name='نام برند')),
            ],
            options={
                'verbose_name': 'لیست برند',
                'verbose_name_plural': 'لیست برند',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'لیست دسته بندی',
                'verbose_name_plural': 'لیست دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('price', models.FloatField(verbose_name='قیمت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='نام برند')),
                ('category_list', models.ManyToManyField(to='product.Category', verbose_name='لیست دسته بندی')),
            ],
            options={
                'verbose_name': 'لیست محصولات ',
                'verbose_name_plural': 'لیست محصولات ',
            },
        ),
    ]
