# Generated by Django 3.2.5 on 2021-07-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_list',
        ),
        migrations.AddField(
            model_name='product',
            name='brands_list',
            field=models.ManyToManyField(to='product.Brand', verbose_name='لیست برند'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='نام دسته بندی'),
        ),
    ]
