# Generated by Django 3.2.5 on 2021-07-14 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210714_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands_list',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='نام برند'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_list',
            field=models.ManyToManyField(to='product.Category', verbose_name='لیست دسته بندی'),
        ),
    ]
